params:
  tool-name: repository-reviewer
  version: 0.1.2
  #email: xxx@mail.com
  #validate-certificate: false
  logs:
    version: 1
    formatters:
      simple:
        format: "%(asctime)s - %(name)s - %(levelname)s: [%(module)s] %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      default:
        level: DEBUG
        handlers:
        - console
        propagate: 'no'
    root:
      level: NOTSET
      handlers: []
  results_format:
    - column_name:  'Nombre de archivo'
      type:           'string'
      details:         'Nombre del archivo/artículo descargado'
    - column_name:  'Estudio primario'
      type:           'boolean'
      details:        'Flag que indica si el artículo será considerado como un estudio primario'
    - column_name:  'Título'
      type:           'string'
      key:            'title'
      details:        'Tìtulo completo del artículo.'
    - column_name:  'Autor(es)'
      type:           'string'
      key:            'author'
      details:        'Autor(es) del artículo en cuestión.'
    - column_name:  'Repositorio'
      type:           'string'
      key:            'repo'
      details:        'Repositorio donde se encontró el artículo'
    - column_name:  'Año de publicación'
      type:           'int32'
      key:            'year'
      details:        'Año en que se publicó el artículo'
    - column_name:  'Fecha de fichaje'
      type:           'datetime64[ns]'
      behaviour:      'automatic'  # FIXME: quizás esto convendría cambiarlo
      details:        'Fecha en que se registró la ficha.'
    - column_name:  'Abstract'
      type:           'string'
      key:            'abstract'
      details:        'Abstract del artículo. Se debe ingresar sin saltos de línea adicionales.'
    - column_name:  'Palabras clave'
      type:           'string'
      details:        'Palabras clave declaradas en el artículo.'
    - column_name:  'Referencias a otros artículos'
      type:           'string'
      details:        'Trabajos de otros autores mencionados en la publicación que podrían ser útiles para ampliar el tema.'
    - column_name: 'Fortalezas'
      type:           'string'
      details:        'Aspectos metodológicos o conceptuales angulares para la investigación.'
    - column_name: 'Debilidades'
      type:           'string'
      details:        'Aspectos que no están bien desarrollados o no resultan claros.'
    - column_name: 'Oportunidades'
      type:           'string'
      details:        'Posibles líneas de trabajo para la tesis.'