repos:
  ieee:
    url: 'https://ieeexploreapi.ieee.org/api/v1/search/articles?parameter'
    apikey: WRITE YOUR API KEY HERE!
    enabled: true
    logger: 'default'

  scopus:
    url: 'https://api.elsevier.com/content/search/scopus?httpAccept=application/json'
    apikey: WRITE YOUR API KEY HERE!
    enabled: true
    logger: 'default'

params:
  tool-name: repository-reviewer
  version: 0.1.2
  #email: xxx@mail.com  
  #validate-certificate: false
  dummy: Another useful params incoming...
  logs:
    version: 1
    formatters:
      simple:
        format: "%(asctime)s - %(name)s - %(levelname)s: [%(module)s] %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      default:
        level: DEBUG
        handlers:
        - console
        propagate: 'no'
    root:
      level: NOTSET
      handlers: []
